 
version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: jobboard_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: jobboard_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data: